name: Graphql CI

on: [push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: kamilkisiela/graphql-inspector@v2.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          schema: 'master:schema.gql'
